name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Run ginkgo tests
      run: go run github.com/onsi/ginkgo/v2/ginkgo -r --procs=3 --compilers=3 --randomize-all --randomize-suites --fail-on-pending --keep-going --race --trace

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1.6
